spring:
    application:
        name: UserConsumer
    main:
      allow-bean-definition-overriding: true
server:
    port: 9401
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  client:
    config:
        feignName:
            read-timeout: 10000